services:
  nats-server:
    image: nats:latest

  gateway:
    build:
      context: ./gateway
      dockerfile: dockerfile.prod
    image: naluengas/microservicios-nestjs:gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}

  # auth-ms change
  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: naluengas/microservicios-nestjs:auth-ms
    environment:
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${AUTH_MONGODB_URL}
      - JWT_SECRET=${JWT_SECRET}

  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
      args:
        - AUTH_MYSQL_URL=${AUTH_MYSQL_URL}
    image: naluengas/microservicios-nestjs:products-ms
    environment:
      - DATABASE_URL=${AUTH_MYSQL_URL}
      - NATS_SERVERS=${NATS_SERVERS}

  # Orders MS
  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - AUTH_POSTGRES_URL=${AUTH_POSTGRES_URL}
    image: naluengas/microservicios-nestjs:orders-ms
    environment:
      - DATABASE_URL=${AUTH_POSTGRES_URL}
      - NATS_SERVERS=${NATS_SERVERS}

  # Payments MS
  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: naluengas/microservicios-nestjs:payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - PAYMENTS_MS_PORT=${PAYMENTS_MS_PORT}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
