name: CI/CD Microservices

on:
  push:
    branches:
      - main
    paths:
      - 'gateway/**'
      - 'auth-ms/**'
      - 'products-ms/**'
      - 'orders-ms/**'
      - 'payments-ms/**'
      - 'docker-compose.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [gateway, auth-ms, products-ms, orders-ms, payments-ms]

    steps:
      # Clona el repositorio principal con los submodules
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # Autenticación en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Construye y sube la imagen de Docker
      - name: Build and push ${{ matrix.service }}
        run: |
          docker build \
            -t naluengas/microservicios-nestjs:${{ matrix.service }} \
            -f ${{ matrix.service }}/dockerfile.prod \
            --platform=linux/amd64 \
            ./${{ matrix.service }}
          docker push naluengas/microservicios-nestjs:${{ matrix.service }}
